### ISSUE TITLE
when start continuous reading its return startInventory() err :-1

### ISSUE THREAD

**Issue by kate88projects** [Justin-roy/Rfid_c72_plugin#6]
Hi, I'm using version 0.0.2 for my device, when using "Start 2d barcode" is working fine, but when press on "Start Continuous Reading" it's return startInventory() err :-1, any idea? my flutter version is 3.16.5 and device Android version is 11, UHF device is CW103_6765 , thanks...

**Comment by Justin-roy** [comment]
I suggest you to use 0.0.1 Version, 0.0.2 is under maintenance. Otherwise best way to use --> create two screen one for 2d barcode reader and second for continues reading. This issue resolve soon thanks for pointing Out.

Note:- **Currently I don't have hardware to test**.

**Comment by kate88projects** [comment]
Hi, thanks for quick reply, i found out is due to I'm open another test apps on background, so it happen this error. After I kill that testing app, then my app can work perfect with version 0.0.2. Thank you again...
